# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WWDemo' do

pod 'CYLTabBarController', '~> 1.13.1'
pod 'Toast', '~> 3.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WWDemo

  target 'WWDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WWDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
